# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main, feature/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - uses: s4u/maven-settings-action@v2.6.0
      with:
        servers: '[{"id": "ossrh", "username": "${{secrets.SONATYPE_USER}}", "password": "${{secrets.SONATYPE_PASS}}"}]'
    - name: Build and Deploy with Maven
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      uses: GabrielBB/xvfb-action@v1
      with:
        run: ./mvnw -B deploy coveralls:report
    - name: Clear Caches
      run: curl -X PURGE https://camo.githubusercontent.com/8b5dee301fc3aee86900e1db08654773df3bd0938cd1d1009be98a34deb7478b/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f6c696e6b2d696e74657273797374656d732f6c69732d636f6d6d6f6e732f62616467652e7376673f6272616e63683d6d6173746572
